=== Brightspace/d2l-lms-launch-darkly-feature-converter-plugin/schemas/instance-multivariate/v1_0.json
{
	"$schema": "http://json-schema.org/draft-06/schema#",
	"$id": "http://schemas.dev.brightspace.com/feature-flags/instance-multivariate/v1_0.json",
	"type": "object",
	"additionalProperties": false,
	"required": [
		"$schema",
		"name",
		"environments",
		"variations"
	],
	"properties": {
		"$schema": {
			"type": "string",
			"title": "The schema which uniquely identifies the feature flag type",
			"enum": [
				"http://schemas.dev.brightspace.com/feature-flags/instance-multivariate/v1_0.json"
			]
		},
		"name": {
			"type": "string",
			"title": "The feature flag name",
			"minLength": 1
		},
		"description": {
			"type": "string",
			"title": "The description of what the feature flag controls",
			"minLength": 1
		},
		"variations": {
			"type": "object",
			"title": "The keyed enumeration of variations. The keys are referenced elsewhere in the document.",
			"additionalProperties": false,
			"minProperties": 2,
			"patternProperties": {
				"^[a-zA-Z_-]+": {
					"$ref": "#/definitions/variation",
					"title": "The variation key"
				}
			}
		},
		"environments": {
			"type": "object",
			"title": "The environment specific targetting rules",
			"additionalProperties": false,
			"required": [
				"production",
				"development"
			],
			"properties": {
				"production": {
					"$ref": "#/definitions/environment",
					"title": "The production targetting rules"
				},
				"development": {
					"$ref": "#/definitions/environment",
					"title": "The development targetting rules"
				}
			}
		},
		"tags": {
			"title": "The tags associated to the feature flag",
			"type": "array",
			"additionalItems": false,
			"minItems": 1,
			"uniqueItems": true,
			"items": {
				"type": "string",
				"pattern": "[a-z0-9_\\-\\.]+"
			}
		}
	},
	"definitions": {
		"environment": {
			"type": "object",
			"additionalProperties": false,
			"required": [
				"defaultVariation"
			],
			"properties": {
				"defaultVariation": {
					"type": "string",
					"title": "The variation to use when neither targets or rules match",
					"minLength": 1,
					"pattern": "^[a-zA-Z_-]+"
				},
				"targets": {
					"type": "array",
					"title": "The explicit instances to target",
					"additionalItems": false,
					"minItems": 1,
					"items": {
						"$ref": "#/definitions/target"
					}
				},
				"rules": {
					"type": "array",
					"title": "The sequential rules which are evaluated when not matched by an explicit target",
					"additionalItems": false,
					"minItems": 1,
					"items": {
						"$ref": "#/definitions/rule"
					}
				}
			}
		},
		"rule": {
			"type": "object",
			"title": "A targetting rule",
			"additionalProperties": false,
			"required": [
				"variation"
			],
			"minProperties": 2,
			"properties": {
				"dataCenters": {
					"type": "array",
					"title": "The set of d2l data centers to target",
					"additionalItems": false,
					"minItems": 1,
					"uniqueItems": true,
					"items": {
						"type": "string",
						"title": "Name of a d2l data center",
						"enum": [
							"ap01",
							"ap02",
							"ca05",
							"ca1d",
							"ca1p",
							"ca3d",
							"ca3p",
							"eu01",
							"us04"
						]
					}
				},
				"instanceTypes": {
					"type": "array",
					"title": "The set of d2l instances types to target",
					"additionalItems": false,
					"minItems": 1,
					"uniqueItems": true,
					"items": {
						"type": "string",
						"enum": [
							"prod",
							"dev",
							"test"
						]
					}
				},
				"versions": {
					"type": "object",
					"title": "The product versions to target",
					"additionalProperties": false,
					"minProperties": 1,
					"properties": {
						"start": {
							"$ref": "#/definitions/version",
							"title": "The version to start targetting at (inclusive)",
							"examples": [
								"10.8.4.12256"
							]
						},
						"end": {
							"$ref": "#/definitions/version",
							"title": "The version to stop targetting at (inclusive)",
							"examples": [
								"10.8.4.99999"
							]
						}
					}
				},
				"variation": {
					"type": "string",
					"title": "The variation to target",
					"minLength": 1,
					"pattern": "^[a-zA-Z_-]+"
				}
			}
		},
		"target": {
			"type": "object",
			"additionalProperties": false,
			"required": [
				"variation"
			],
			"minProperties": 2,
			"properties": {
				"instanceNames": {
					"type": "array",
					"title": "The set of instance names to target",
					"additionalItems": false,
					"minItems": 1,
					"uniqueItems": true,
					"items": {
						"type": "string",
						"title": "The instance names to target",
						"minLength": 1
					}
				},
				"instanceIds": {
					"type": "array",
					"title": "The set of instance ids to target",
					"additionalItems": false,
					"minItems": 1,
					"uniqueItems": true,
					"items": {
						"type": "string",
						"title": "The instance ids to target",
						"pattern": "^[0-9a-f]{8}(-[0-9a-f]{4}){3}-[0-9a-f]{12}"
					}
				},
				"variation": {
					"type": "string",
					"title": "The variation to target",
					"minLength": 1,
					"pattern": "^[a-zA-Z_-]+"
				}
			}
		},
		"variation": {
			"type": "object",
			"additionalProperties": false,
			"required": [
				"value"
			],
			"properties": {
				"name": {
					"type": "string",
					"title": "The human readable name of the variation",
					"minLength": 1
				},
				"description": {
					"type": "string",
					"title": "The description of what the variation controls",
					"minLength": 1
				},
				"value": {
					"type": [
						"string",
						"integer"
					],
					"title": "The value of the variaent"
				}
			}
		},
		"version": {
			"type": "string",
			"pattern": "^[1-9][0-9]\\.[1-9]?[0-9]\\.[1-9]?[0-9]\\.[1-9]?[0-9]{0,4}$"
		}
	}
}

=== Brightspace/d2l-lms-launch-darkly-feature-converter-plugin/examples/instance-multivariate.feature.json
{
	"$schema": "http://schemas.dev.brightspace.com/feature-flags/instance-multivariate/v1_0.json",
	"name": "Panda Classification",
	"description": "WWF feature flag",
	"variations": {
		"bear": {
			"name": "Bear",
			"description": "A normal panda bear.",
			"value": "0"
		},
		"trash": {
			"name": "Trash",
			"description": "A beast that wanders the street at night.",
			"value": "1"
		}
	},
	"environments": {
		"production": {
			"defaultVariation": "bear",
			"targets": [
				{
					"instanceNames": [
						"my_academy"
					],
					"variation": "trash"
				}
			]
		},
		"development": {
			"defaultVariation": "bear",
			"targets": [
				{
					"instanceIds": [
						"f3c33018-d9dd-447a-a7bc-7428b2e458e6",
						"2ddf1282-0610-4d66-b25e-b207c42b18f3"
					],
					"variation": "trash"
				},
				{
					"instanceIds": [
						"2954f095-3c9e-4be1-b222-e5a8f2618ec7"
					],
					"variation": "bear"
				}
			],
			"rules": [
				{
					"dataCenters": [
						"eu01"
					],
					"variation": "bear"
				},
				{
					"dataCenters": [
						"us04"
					],
					"instanceTypes": [
						"prod",
						"dev"
					],
					"versions": {
						"start": "10.8.4.0",
						"end": "10.8.4.99999"
					},
					"variation": "trash"
				}
			]
		}
	},
	"tags": [
		"animals"
	]
}
