=== Brightspace/d2l-lms-launch-darkly-feature-converter-plugin/schemas/instance-multivariate/v2_1.json
{
	"$schema": "http://json-schema.org/draft-06/schema#",
	"$id": "http://schemas.featureflags.d2ldev.com/lms/instance-multivariate/v2_1.json",
	"type": "object",
	"additionalProperties": false,
	"required": [
		"$schema",
		"name",
		"environments",
		"variations"
	],
	"properties": {
		"$schema": {
			"type": "string",
			"title": "The schema which uniquely identifies the feature flag type",
			"enum": [
				"http://schemas.featureflags.d2ldev.com/lms/instance-multivariate/v2_1.json"
			]
		},
		"name": {
			"type": "string",
			"title": "The feature flag name",
			"minLength": 1
		},
		"description": {
			"type": "string",
			"title": "The description of what the feature flag controls",
			"minLength": 1
		},
		"rallyId": {
			"type": "string",
			"title": "The rally identifier for the associated defect/feature.",
			"pattern": "^(DE|F|US)\\d+"
		},
		"variations": {
			"type": "array",
			"title": "The keyed enumeration of variations. The keys are referenced elsewhere in the document.",
			"additionalItems": false,
			"minItems": 2,
			"items": {
				"$ref": "#/definitions/variation"
			}
		},
		"environments": {
			"type": "object",
			"title": "The environment specific targetting rules",
			"additionalProperties": false,
			"required": [
				"production",
				"development"
			],
			"properties": {
				"production": {
					"$ref": "#/definitions/environment",
					"title": "The production targetting rules"
				},
				"development": {
					"$ref": "#/definitions/environment",
					"title": "The development targetting rules"
				}
			}
		},
		"tags": {
			"title": "The tags associated to the feature flag",
			"type": "array",
			"additionalItems": false,
			"minItems": 1,
			"uniqueItems": true,
			"items": {
				"type": "string",
				"pattern": "[a-z0-9_\\-\\.]+"
			}
		}
	},
	"definitions": {
		"environment": {
			"type": "object",
			"additionalProperties": false,
			"required": [
				"defaultVariation"
			],
			"properties": {
				"defaultVariation": {
					"type": "string",
					"title": "The variation to use when neither targets or rules match",
					"minLength": 1,
					"pattern": "^[a-zA-Z0-9_-]+$"
				},
				"targets": {
					"type": "array",
					"title": "The explicit instances to target",
					"additionalItems": false,
					"minItems": 1,
					"items": {
						"$ref": "#/definitions/target"
					}
				},
				"rules": {
					"type": "array",
					"title": "The sequential rules which are evaluated when not matched by an explicit target",
					"additionalItems": false,
					"minItems": 1,
					"items": {
						"$ref": "#/definitions/rule"
					}
				}
			}
		},
		"rule": {
			"type": "object",
			"title": "A targetting rule",
			"additionalProperties": false,
			"required": [
				"variation"
			],
			"minProperties": 2,
			"properties": {
				"dataCenters": {
					"type": "array",
					"title": "The set of d2l data centers to target",
					"additionalItems": false,
					"minItems": 1,
					"uniqueItems": true,
					"items": {
						"type": "string",
						"title": "Name of a d2l data center",
						"enum": [
							"ap01",
							"ap02",
							"ca05",
							"ca1d",
							"ca1p",
							"ca3d",
							"ca3p",
							"eu01",
							"us04"
						]
					}
				},
				"instanceTypes": {
					"type": "array",
					"title": "The set of d2l instances types to target",
					"additionalItems": false,
					"minItems": 1,
					"uniqueItems": true,
					"items": {
						"type": "string",
						"enum": [
							"prod",
							"dev",
							"test"
						]
					}
				},
				"versions": {
					"type": "object",
					"title": "The product versions to target",
					"additionalProperties": false,
					"minProperties": 1,
					"properties": {
						"start": {
							"$ref": "#/definitions/version",
							"title": "The version to start targetting at (inclusive)",
							"examples": [
								"10.8.4.12256"
							]
						},
						"end": {
							"$ref": "#/definitions/version",
							"title": "The version to stop targetting at (inclusive)",
							"examples": [
								"10.8.4.99999"
							]
						}
					}
				},
				"variation": {
					"type": "string",
					"title": "The variation to target",
					"minLength": 1,
					"pattern": "^[a-zA-Z0-9_-]+$"
				}
			}
		},
		"target": {
			"type": "object",
			"additionalProperties": false,
			"required": [
				"variation"
			],
			"minProperties": 2,
			"properties": {
				"instances": {
					"type": "array",
					"title": "The set of instances to target",
					"additionalItems": false,
					"minItems": 1,
					"uniqueItems": true,
					"items": {
						"anyOf": [
							{
								"$ref": "#/definitions/instanceIdTarget"
							},
							{
								"$ref": "#/definitions/instanceTarget"
							}
						]
					}
				},
				"instanceNames": {
					"type": "array",
					"title": "The set of instance names to target",
					"additionalItems": false,
					"minItems": 1,
					"uniqueItems": true,
					"items": {
						"type": "string",
						"title": "The instance names to target",
						"minLength": 1
					}
				},
				"instanceIds": {
					"type": "array",
					"title": "The set of instance ids to target",
					"additionalItems": false,
					"minItems": 1,
					"uniqueItems": true,
					"items": {
						"$ref": "#/definitions/instanceIdTarget"
					}
				},
				"variation": {
					"type": "string",
					"title": "The variation to target",
					"minLength": 1,
					"pattern": "^[a-zA-Z0-9_-]+$"
				}
			}
		},
		"instanceIdTarget": {
			"type": "string",
			"title": "The instance id to target",
			"pattern": "^[0-9a-f]{8}(-[0-9a-f]{4}){3}-[0-9a-f]{12}"
		},
		"instanceTarget": {
			"type": "object",
			"additionalProperties": false,
			"required": [
				"instanceId",
				"comments"
			],
			"properties": {
				"instanceId": {
					"$ref": "#/definitions/instanceIdTarget"
				},
				"comments": {
					"type": "string",
					"title": "The comments about the instance",
					"minLength": 1
				}
			}
		},
		"variation": {
			"type": "object",
			"additionalProperties": false,
			"required": [
				"key",
				"value"
			],
			"properties": {
				"key": {
					"type": "string",
					"title": "The variation key",
					"minLength": 1,
					"pattern": "^[a-zA-Z0-9_-]+$"
				},
				"name": {
					"type": "string",
					"title": "The human readable name of the variation",
					"minLength": 1
				},
				"description": {
					"type": "string",
					"title": "The description of what the variation controls",
					"minLength": 1
				},
				"value": {
					"type": [
						"string",
						"integer"
					],
					"title": "The value of the variaent"
				}
			}
		},
		"version": {
			"type": "string",
			"pattern": "^[1-9][0-9]\\.[1-9]?[0-9]\\.[1-9]?[0-9]\\.[1-9]?[0-9]{0,4}$"
		}
	}
}

=== Brightspace/d2l-lms-launch-darkly-feature-converter-plugin/test/testCases/endToEnd/instance-multivariate-v2_1/definition.json
{
	"$schema": "http://schemas.featureflags.d2ldev.com/lms/instance-multivariate/v2_1.json",
	"name": "Fruit",
	"description": "A flag for the extra type of fruit grown on the field",
	"rallyId": "DE77777",
	"tags": [
		"mocha",
		"test"
	],
	"variations": [
		{
			"key": "none",
			"name": "No Fruit",
			"description": "No fruit is grown",
			"value": 0
		},
		{
			"key": "bananas",
			"name": "Bananas",
			"description": "Bananas are grown",
			"value": 1
		},
		{
			"key": "grapes",
			"name": "Grapes",
			"description": "Grapes are grown",
			"value": 2
		}
	],
	"environments": {
		"production": {
			"defaultVariation": "none",
			"targets": [
				{
					"instanceIds": [
						"3d005b79-d38c-4893-a507-77e7f78fe2fa",
						"50b95e47-4f69-4219-8d1d-3c13af3479de"
					],
					"variation": "bananas"
				},
				{
					"instances": [
						{
							"instanceId": "0b801fe6-82b8-44ee-acbe-1b563fa5c6ff",
							"comments": "Something deep and meaningful"
						}
					],
					"variation": "grapes"
				}
			]
		},
		"development": {
			"defaultVariation": "grapes",
			"rules": [
				{
					"versions": {
						"start": "10.8.4.0"
					},
					"variation": "none"
				},
				{
					"dataCenters": [
						"us04"
					],
					"variation": "bananas"
				}
			]
		}
	}
}
