=== Brightspace/d2l-lms-launch-darkly-feature-converter-plugin/schemas/org-boolean/v1_2.json
{
	"$schema": "http://json-schema.org/draft-06/schema#",
	"$id": "http://schemas.featureflags.d2ldev.com/lms/org-boolean/v1_2.json",
	"type": "object",
	"additionalProperties": false,
	"required": [
		"$schema",
		"name",
		"environments"
	],
	"properties": {
		"$schema": {
			"type": "string",
			"title": "The schema which uniquely identifies the feature flag type",
			"enum": [
				"http://schemas.featureflags.d2ldev.com/lms/org-boolean/v1_2.json"
			]
		},
		"name": {
			"type": "string",
			"title": "The feature flag name",
			"minLength": 1
		},
		"description": {
			"type": "string",
			"title": "The description of what the feature flag controls",
			"minLength": 1
		},
		"rallyId": {
			"type": "string",
			"title": "The rally identifier for the associated defect/feature.",
			"pattern": "^(DE|F|US)\\d+"
		},
		"variations": {
			"type": "object",
			"title": "The keyed enumeration of variations. The keys are referenced elsewhere in the document.",
			"additionalProperties": false,
			"required": [
				"true",
				"false"
			],
			"properties": {
				"true": {
					"$ref": "#/definitions/variation",
					"title": "The true variation key"
				},
				"false": {
					"$ref": "#/definitions/variation",
					"title": "The false variation key"
				}
			}
		},
		"environments": {
			"type": "object",
			"title": "The environment specific targetting rules",
			"additionalProperties": false,
			"required": [
				"production",
				"development"
			],
			"properties": {
				"production": {
					"$ref": "#/definitions/environment",
					"title": "The production targetting rules"
				},
				"development": {
					"$ref": "#/definitions/environment",
					"title": "The development targetting rules"
				}
			}
		},
		"tags": {
			"title": "The tags associated to the feature flag",
			"type": "array",
			"additionalItems": false,
			"minItems": 1,
			"uniqueItems": true,
			"items": {
				"type": "string",
				"pattern": "[a-z0-9_\\-\\.]+"
			}
		}
	},
	"definitions": {
		"environment": {
			"type": "object",
			"additionalProperties": false,
			"required": [
				"defaultVariation"
			],
			"properties": {
				"defaultVariation": {
					"type": "string",
					"title": "The variation to use when neither targets or rules match",
					"enum": [
						"true",
						"false"
					]
				},
				"targets": {
					"type": "array",
					"title": "The explicit instances to target",
					"additionalItems": false,
					"minItems": 1,
					"items": {
						"$ref": "#/definitions/target"
					}
				},
				"rules": {
					"type": "array",
					"title": "The sequential rules which are evaluated when not matched by an explicit target",
					"additionalItems": false,
					"minItems": 1,
					"items": {
						"$ref": "#/definitions/rule"
					}
				}
			}
		},
		"rule": {
			"type": "object",
			"title": "A targetting rule",
			"additionalProperties": false,
			"required": [
				"variation"
			],
			"minProperties": 2,
			"properties": {
				"awsRegions": {
					"type": "array",
					"title": "The aws region the tenant is configured to store their data in",
					"additionalItems": false,
					"minItems": 1,
					"uniqueItems": true,
					"items": {
						"type": "string",
						"title": "The aws region",
						"enum": [
							"ap-southeast-1",
							"ap-southeast-2",
							"ca-central-1",
							"eu-west-1",
							"us-east-1"
						]
					}
				},
				"dataCenters": {
					"type": "array",
					"title": "The set of d2l data centers to target",
					"additionalItems": false,
					"minItems": 1,
					"uniqueItems": true,
					"items": {
						"type": "string",
						"title": "Name of a d2l data center",
						"enum": [
							"ap01",
							"ap02",
							"ca05",
							"ca1d",
							"ca1p",
							"ca3d",
							"ca3p",
							"eu01",
							"us04"
						]
					}
				},
				"instanceTypes": {
					"type": "array",
					"title": "The set of d2l instances types to target",
					"additionalItems": false,
					"minItems": 1,
					"uniqueItems": true,
					"items": {
						"type": "string",
						"enum": [
							"prod",
							"dev",
							"test"
						]
					}
				},
				"versions": {
					"type": "object",
					"title": "The product versions to target",
					"additionalProperties": false,
					"minProperties": 1,
					"properties": {
						"start": {
							"$ref": "#/definitions/version",
							"title": "The version to start targetting at (inclusive)",
							"examples": [
								"10.8.4.12256"
							]
						},
						"end": {
							"$ref": "#/definitions/version",
							"title": "The version to stop targetting at (inclusive)",
							"examples": [
								"10.8.4.99999"
							]
						}
					}
				},
				"variation": {
					"type": "string",
					"title": "The variation to target",
					"enum": [
						"true",
						"false"
					]
				}
			}
		},
		"target": {
			"type": "object",
			"additionalProperties": false,
			"required": [
				"variation"
			],
			"minProperties": 2,
			"properties": {
				"tenants": {
					"type": "array",
					"title": "The set of tenants to target",
					"additionalItems": false,
					"minItems": 1,
					"uniqueItems": true,
					"items": {
						"anyOf": [
							{
								"$ref": "#/definitions/tenantIdTarget"
							},
							{
								"$ref": "#/definitions/tenantTarget"
							}
						]
					}
				},
				"tenantDomains": {
					"type": "array",
					"title": "The set of tenant domains to target",
					"additionalItems": false,
					"minItems": 1,
					"uniqueItems": true,
					"items": {
						"type": "string",
						"title": "The tenant domains to target",
						"minLength": 1
					}
				},
				"tenantIds": {
					"type": "array",
					"title": "The set of tenant ids to target",
					"additionalItems": false,
					"minItems": 1,
					"uniqueItems": true,
					"items": {
						"$ref": "#/definitions/tenantIdTarget"
					}
				},
				"variation": {
					"type": "string",
					"title": "The variation to target",
					"enum": [
						"true",
						"false"
					]
				}
			}
		},
		"tenantIdTarget": {
			"type": "string",
			"title": "The tenant id to target",
			"pattern": "^[0-9a-f]{8}(-[0-9a-f]{4}){3}-[0-9a-f]{12}"
		},
		"tenantTarget": {
			"type": "object",
			"additionalProperties": false,
			"required": [
				"tenantId",
				"comments"
			],
			"properties": {
				"tenantId": {
					"$ref": "#/definitions/tenantIdTarget"
				},
				"comments": {
					"type": "string",
					"title": "The comments about the tenant",
					"minLength": 1
				}
			}
		},
		"variation": {
			"type": "object",
			"additionalProperties": false,
			"required": [
				"name"
			],
			"properties": {
				"name": {
					"type": "string",
					"title": "The human readable name of the variation",
					"minLength": 1
				},
				"description": {
					"type": "string",
					"title": "The description of what the variation controls",
					"minLength": 1
				}
			}
		},
		"version": {
			"type": "string",
			"pattern": "^[1-9][0-9]\\.[1-9]?[0-9]\\.[1-9]?[0-9]\\.[1-9]?[0-9]{0,4}$"
		}
	}
}

=== Brightspace/d2l-lms-launch-darkly-feature-converter-plugin/test/testCases/endToEnd/org-boolean-v1_2/definition.json
{
	"$schema": "http://schemas.featureflags.d2ldev.com/lms/org-boolean/v1_2.json",
	"name": "Switch",
	"description": "Simple on/off switch",
	"rallyId": "DE77777",
	"tags": [
		"mocha",
		"test"
	],
	"variations": {
		"true": {
			"name": "On",
			"description": "Turns the switch on"
		},
		"false": {
			"name": "Off",
			"description": "Turns the switch off"
		}
	},
	"environments": {
		"production": {
			"defaultVariation": "false",
			"targets": [
				{
					"tenantIds": [
						"aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"
					],
					"variation": "true"
				},
				{
					"tenantIds": [
						"bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"
					],
					"variation": "false"
				}
			]
		},
		"development": {
			"defaultVariation": "true",
			"rules": [
				{
					"versions": {
						"start": "10.8.4.0"
					},
					"variation": "false"
				}
			]
		}
	}
}
